def lstm_config(unit: str):
    match unit:
        case "1":
            return {
                "TIMESTEPS": 2016,
                "HORIZON": 2016,
                "PREPARE_DATA": 1,
                "INPUT_COLS": [
                    "SKR1.24VDC VOLTAGE BUSBAR A",
                    "SKR1.24VDC VOLTAGE BUSBAR B",
                    "SKR1.ACTIVE POWER U1",
                    "SKR1.ACTIVE PWR",
                    "SKR1.BUSBAR      VOLTAGE",
                    "SKR1.BUSBAR VOLTAGE",
                    "SKR1.Current Inc To Trafo2",
                    "SKR1.Current Out To PH",
                    "SKR1.DIESEL 1 STATOR CURRENT",
                    "SKR1.DIESEL 1 STATOR VOLTAGE",
                    "SKR1.DIESEL 2 STATOR CURRENT",
                    "SKR1.HOT AIR TEMPERATURE1 U1",
                    "SKR1.HOT AIR TEMPERATURE2 U1",
                    "SKR1.HOT AIR TEMPERATURE3 U1",
                    "SKR1.HOT AIR TEMPERATURE4 U1",
                    "SKR1.HOT AIR TEMPERATURE5 U1",
                    "SKR1.HOT AIR TEMPERATURE6 U1",
                    "SKR1.LO GUIDE BRG METAL 1 U1",
                    "SKR1.LO GUIDE BRG METAL 2 U1",
                    "SKR1.LO GUIDE BRGOIL TEMP U1",
                    "SKR1.LOAD LIMITERPOSITION U 1",
                    "SKR1.MDB Voltage Busbar A",
                    "SKR1.METAL TEMP 1 U1",
                    "SKR1.OIL TEMP. U1",
                    "SKR1.REACTIVE    PWR UNIT 1",
                    "SKR1.REACTIVE POWER U1",
                    "SKR1.ROTOR CURR  UNIT 1",
                    "SKR1.ROTOR VOLT  UNIT 1",
                    "SKR1.STATOR CORE TEMP1 U1",
                    "SKR1.STATOR CORE TEMP2 U1",
                    "SKR1.STATOR CURR UNIT 1",
                    "SKR1.STATOR VOLT UNIT 1",
                    "SKR1.STATOR WIND TEMP1 U1",
                    "SKR1.STATOR WIND TEMP2 U1",
                    "SKR1.STATOR WIND TEMP3 U1",
                    "SKR1.STATOR WIND TEMP4 U1",
                    "SKR1.STATOR WIND TEMP5 U1",
                    "SKR1.STATOR WIND TEMP6 U1",
                    "SKR1.TAIL WATER  PRESSURE",
                    "SKR1.THRUST BRG  METAL 1 U1",
                    "SKR1.THRUST BRG  METAL 2 U1",
                    "SKR1.THRUST BRG  METAL 3 U1",
                    "SKR1.TURB SPEED  DROOP UNIT 1",
                    "SKR1.TURB SPEED  UNIT 1",
                    "SKR1.TURBINE     DISCHARGE",
                    "SKR1.UP GD&TH BRGOIL TEMP U1",
                    "SKR1.UP GUIDE BRG METAL 1 U1",
                    "SKR1.UP GUIDE BRG METAL 2 U1",
                    "SKR1.Voltage Inc Fr 5MVA Traf",
                    "SKR1.WATER UPSTREAM PRESSURE",
                    "SKR1.WICKET GATE POSITION",
                    #"SKR1.Discharge Debit ",
                    #"SKR1.Generator Turbine Guide ",
                    "SKR1.Generator Lower Guide Bearing Horizontal Vibration",
                    "SKR1.Generator Lower Guide Bearing Vertical Vibration",
                    "SKR1.Generator Lower Guide Bearing Axial Vibration",
                    "SKR1.Generator Upper Guide Bearing Horizontal Vibration",
                    "SKR1.Generator Upper Guide Bearing Vertical Vibration",
                    "SKR1.Generator Upper Guide Bearing Axial Vibration",
                    "SKR1.Generator Turbine Guide Bearing Horizontal Vibration",
                    "SKR1.Generator Turbine Guide Bearing Vertical Vibration",
                    "SKR1.Generator Turbine Guide Bearing Axial Vibration"
                ],
                "TARGET_COLS": [
                    "SKR1.Generator Lower Guide Bearing Horizontal Vibration",
                    "SKR1.Generator Lower Guide Bearing Vertical Vibration",
                    "SKR1.Generator Lower Guide Bearing Axial Vibration",
                    "SKR1.Generator Upper Guide Bearing Horizontal Vibration",
                    "SKR1.Generator Upper Guide Bearing Vertical Vibration",
                    "SKR1.Generator Upper Guide Bearing Axial Vibration",
                    "SKR1.Generator Turbine Guide Bearing Horizontal Vibration",
                    "SKR1.Generator Turbine Guide Bearing Vertical Vibration",
                    "SKR1.Generator Turbine Guide Bearing Axial Vibration"
                ],
                "TARGET_COLS_PRED": [
                    "SKR1.LO GUIDE BRGOIL TEMP U1.prediksi",
                    "SKR1.METAL TEMP 1 U1.prediksi",
                    "SKR1.OIL TEMP. U1.prediksi",
                    "SKR1.UP GD&TH BRGOIL TEMP U1.prediksi",
                    "SKR1.THRUST BRG  METAL 1 U1.prediksi",
                    "SKR1.THRUST BRG  METAL 2 U1.prediksi",
                    "SKR1.THRUST BRG  METAL 3 U1.prediksi",
                    "SKR1.STATOR CORE TEMP1 U1.prediksi",
                    "SKR1.STATOR CORE TEMP2 U1.prediksi",
                    "SKR1.STATOR WIND TEMP1 U1.prediksi",
                    "SKR1.STATOR WIND TEMP2 U1.prediksi",
                    "SKR1.STATOR WIND TEMP3 U1.prediksi",
                    "SKR1.STATOR WIND TEMP4 U1.prediksi",
                    "SKR1.STATOR WIND TEMP5 U1.prediksi",
                    "SKR1.STATOR WIND TEMP6 U1.prediksi",
                    "SKR1.Generator Lower Guide Bearing Horizontal Vibration.prediksi",
                    "SKR1.Generator Lower Guide Bearing Vertical Vibration.prediksi",
                    "SKR1.Generator Lower Guide Bearing Axial Vibration.prediksi",
                    "SKR1.Generator Upper Guide Bearing Horizontal Vibration.prediksi",
                    "SKR1.Generator Upper Guide Bearing Vertical Vibration.prediksi",
                    "SKR1.Generator Upper Guide Bearing Axial Vibration.prediksi",
                    "SKR1.Generator Turbine Guide Bearing Horizontal Vibration.prediksi",
                    "SKR1.Generator Turbine Guide Bearing Vertical Vibration.prediksi",
                    "SKR1.Generator Turbine Guide Bearing Axial Vibration.prediksi",
                ]
            }
        case "2":
            return {
                "TIMESTEPS": 2016,
                "HORIZON": 2016,
                "PREPARE_DATA": 1,
                "INPUT_COLS": [
                    "SKR2.ACTIVE PWR",
                    "SKR2.ACTIVE PWR  UNIT 2"
                    "SKR2.AROTOR CURR  UNIT 2",
                    "SKR2.HOT AIR TEMPERATURE 1 U2",
                    "SKR2.HOT AIR TEMPERATURE2 U2",
                    "SKR2.HOT AIR TEMPERATURE3 U2",
                    "SKR2.HOT AIR TEMPERATURE4 U2",
                    "SKR2.HOT AIR TEMPERATURE5 U2",
                    "SKR2.HOT AIR TEMPERATURE6 U2",
                    "SKR2.LO GUIDE BRG METAL 1 U2",
                    "SKR2.LO GUIDE BRG METAL 2 U2",
                    "SKR2.LO GUIDE BRGOIL TEMP U2",
                    "SKR2.LOAD LIMITERPOSITION U 2",
                    "SKR2.METAL TEMP 1 U2",
                    "SKR2.METAL TEMP 2 U2",
                    "SKR2.OIL TEMP. U2",
                    "SKR2.REACTIVE    PWR UNIT 2",
                    "SKR2.SPIRAL CASE PRESS UNIT 2",
                    "SKR2.STATOR CORE TEMP1 U2",
                    "SKR2.STATOR CORE TEMP2 U2",
                    "SKR2.STATOR CURR UNIT 2",
                    "SKR2.STATOR VOLT UNIT2",
                    "SKR2.STATOR WIND TEMP 4 U2",
                    "SKR2.STATOR WIND TEMP1 U2",
                    "SKR2.STATOR WIND TEMP2 U2",
                    "SKR2.STATOR WIND TEMP3 U2",
                    "SKR2.STATOR WIND TEMP5 U2",
                    "SKR2.STATOR WIND TEMP6 U2",
                    "SKR2.TAIL WATER  PRESSURE U2",
                    "SKR2.THRUST BRG  METAL 1 U2",
                    "SKR2.THRUST BRG  METAL 2 U2",
                    "SKR2.THRUST BRG  METAL 3 U2",
                    "SKR2.TURB SPEED  DROOP UNIT 2",
                    "SKR2.TURB SPEED  UNIT 2",
                    "SKR2.TURBINE     DISCHARGE",
                    "SKR2.TURBINE DISCHARGE U2",
                    "SKR2.UP GUIDE BRGMETAL TEMP 1",
                    "SKR2.UP GUIDE BRGMTL 2 U2",
                    "SKR2.UPPER GUIDE AND THRUST B",
                    "SKR2.WICKET GATE POSITION U2",
                    "SKR2.WTR UPSTREAMPRESSURE U2",
                    "SKR2.Generator Turbine Guide Bearing Horizontal Vibration",
                    "SKR2.Generator Turbine Guide Bearing Vertical Vibration",
                    "SKR2.Generator Turbine Guide Bearing Axial Vibration",
                    "SKR2.Generator Lower Guide Bearing Horizontal Vibration",
                    "SKR2.Generator Lower Guide Bearing Vertical Vibration",
                    "SKR2.Generator Lower Guide Bearing Axial Vibration",
                    "SKR2.Generator Upper Guide Bearing Horizontal Vibration",
                    "SKR2.Generator Upper Guide Bearing Vertical Vibration",
                    "SKR2.Generator Upper Guide Bearing Axial Vibration",
                    "SKR2.Discharge Debit"
                ]
            }
        case "3":
            return {
                "TIMESTEPS": 2016,
                "HORIZON": 2016,
                "PREPARE_DATA": 1,
                "INPUT_COLS": [
                    "SKR3.ACTIVE PWR",
                    "SKR3.ACTIVE PWR  UNIT 3",
                    "SKR3.BUS BAR VOLTAGE U3",
                    "SKR3.HOT AIR TEMPERATURE1 U3",
                    "SKR3.HOT AIR TEMPERATURE2 U3",
                    "SKR3.HOT AIR TEMPERATURE3 U3",
                    "SKR3.HOT AIR TEMPERATURE4 U3",
                    "SKR3.HOT AIR TEMPERATURE5 U3",
                    "SKR3.HOT AIR TEMPERATURE6 U3",
                    "SKR3.LO GUIDE BRG METAL 1 U3",
                    "SKR3.LO GUIDE BRG METAL 2 U3",
                    "SKR3.LO GUIDE BRGOIL TEMP U3",
                    "SKR3.LOAD LIMITERPOSITION U 3",
                    "SKR3.METAL TEMP 1 U3",
                    "SKR3.METAL TEMP 2 U3",
                    "SKR3.OIL TEMP. U3",
                    "SKR3.OIL TEMP. U3 MAIN TRAFO",
                    "SKR3.REACTIVE    PWR UNIT 3",
                    "SKR3.ROTOR CURR  UNIT 3",
                    "SKR3.ROTOR VOLT  UNIT 3",
                    "SKR3.SPIRAL CASE PRESS UNIT 3",
                    "SKR3.STATOR CORE TEMP1 U3",
                    "SKR3.STATOR CORE TEMP2 U3",
                    "SKR3.STATOR CURR UNIT 3",
                    "SKR3.STATOR VOLT UNIT 3",
                    "SKR3.STATOR WIND TEMP1 U3",
                    "SKR3.STATOR WIND TEMP2 U3",
                    "SKR3.STATOR WIND TEMP3 U3",
                    "SKR3.STATOR WIND TEMP4 U3",
                    "SKR3.STATOR WIND TEMP5 U3",
                    "SKR3.STATOR WIND TEMP6 U3",
                    "SKR3.TAIL WATER  PRESSURE U3",
                    "SKR3.THRUST BRG  METAL 1 U3",
                    "SKR3.THRUST BRG  METAL 2 U3",
                    "SKR3.THRUST BRG  METAL 3 U3",
                    "SKR3.TURB SPEED  DROOP UNIT 3",
                    "SKR3.TURB SPEED  UNIT 3",
                    "SKR3.TURBINE DISCHARGE U3",
                    "SKR3.UP GD&TH BRGOIL TEMP U3",
                    "SKR3.UP GUIDE BRG METAL 1 U3",
                    "SKR3.UP GUIDE BRG METAL 2 U3",
                    "SKR3.WATER UPSTREAM PRESS U3",
                    "SKR3.WICKET GATE POSITION U3",
                    "SKR3.Generator Turbine Guide Bearing Horizontal Vibration",
                    "SKR3.Generator Turbine Guide Bearing Vertical Vibration",
                    "SKR3.Generator Turbine Guide Bearing Axial Vibration",
                    "SKR3.Generator Lower Guide Bearing Horizontal Vibration",
                    "SKR3.Generator Lower Guide Bearing Vertical Vibration",
                    "SKR3.Generator Lower Guide Bearing Axial Vibration",
                    "SKR3.Generator Upper Guide Bearing Horizontal Vibration",
                    "SKR3.Generator Upper Guide Bearing Vertical Vibration",
                    "SKR3.Generator Upper Guide Bearing Axial Vibration",
                    "SKR3.Discharge Debit"
                ]
            }
        case "4":
            return {
                "TIMESTEPS": 2016,
                "HORIZON": 2016,
                "PREPARE_DATA": 1,
                "INPUT_COLS": [
                    "SKR4.ACTIVE POWER UNIT 4",
                    "SKR4.ACTIVE PWR",
                    "SKR4.ACTIVE PWR  UNIT4",
                    "SKR4.BUSBAR VOLTAGE UNIT4",
                    "SKR4.HOT AIR TEMPERATURE 1 U4",
                    "SKR4.HOT AIR TEMPERATURE 2 U4",
                    "SKR4.HOT AIR TEMPERATURE 4 U4",
                    "SKR4.HOT AIR TEMPERATURE3 U4",
                    "SKR4.HOT AIR TEMPERATURE5 U4",
                    "SKR4.HOT AIR TEMPERATURE6 U4",
                    "SKR4.LO GUIDE BRGMETAL 1 U4",
                    "SKR4.LO GUIDE BRGMETAL 2 U4",
                    "SKR4.LO GUIDE BRGOIL TEMP U4",
                    "SKR4.LOAD LIMITERPOSITION U 4",
                    "SKR4.METAL TEMP 2 U4",
                    "SKR4.REACTIVE    PWR UNIT 4",
                    "SKR4.ROTOR CURR  UNIT 4",
                    "SKR4.ROTOR VOLT  UNIT 4",
                    "SKR4.SPIRAL CASE PRESS UNIT 4",
                    "SKR4.STATOR CORE TEMP 2 U4",
                    "SKR4.STATOR CORE TEMP1 UNIT4",
                    "SKR4.STATOR CURR UNIT 4",
                    "SKR4.STATOR VOLT UNIT 4",
                    "SKR4.STATOR WIND TEMP 1 U4",
                    "SKR4.STATOR WIND TEMP 2 U4",
                    "SKR4.STATOR WIND TEMP 6 U4",
                    "SKR4.STATOR WIND TEMP3 UNIT4",
                    "SKR4.STATOR WIND TEMP4 UNIT4",
                    "SKR4.STATOR WIND TEMP5 UNIT4",
                    "SKR4.TEMP OIL GOVERNOR U4",
                    "SKR4.TEMP OIL MAIN TRAFO U4",
                    "SKR4.TEMP TURBIN METAL 1 U4",
                    "SKR4.TEMP TURBIN METAL 2 U4",
                    "SKR4.THRUST BRG  METAL 1 U4",
                    "SKR4.THRUST BRG  METAL 2 U4",
                    "SKR4.THRUST BRG  METAL 3 U4",
                    "SKR4.TURB SPEED  DROOP UNIT 4",
                    "SKR4.TURB SPEED  UNIT 4",
                    "SKR4.TURBIN OIL TEMP. U4",
                    "SKR4.TURBINE     DISCHARGE",
                    "SKR4.TURBINE DISCHARGE UNIT4",
                    "SKR4.UP GD&TH BRGOIL TEMP U4",
                    "SKR4.UP GUIDE BRG METAL 1 U4",
                    "SKR4.UP GUIDE BRGMETAL 2 U4",
                    "SKR4.WICKET GATE POSITION U4",
                    "SKR4.WTR UPSTREAMPRESSURE U4",
                    "SKR4.Generator Turbine Guide Bearing Horizontal Vibration",
                    "SKR4.Generator Turbine Guide Bearing Vertical Vibration",
                    "SKR4.Generator Turbine Guide Bearing Axial Vibration",
                    "SKR4.Generator Lower Guide Bearing Horizontal Vibration",
                    "SKR4.Generator Lower Guide Bearing Vertical Vibration",
                    "SKR4.Generator Lower Guide Bearing Axial Vibration",
                    "SKR4.Generator Upper Guide Bearing Horizontal Vibration",
                    "SKR4.Generator Upper Guide Bearing Vertical Vibration",
                    "SKR4.Generator Upper Guide Bearing Axial Vibration",
                    "SKR4.Discharge Debit"
                ]
            }
        case _:
            raise ValueError(f"No config defined for unit = {unit}")