UNIT1_INPUT_COLS  = [
    "SKR1.24VDC VOLTAGE BUSBAR A",
    "SKR1.24VDC VOLTAGE BUSBAR B",
    "SKR1.ACTIVE POWER U1",
    "SKR1.ACTIVE PWR",
    "SKR1.BUSBAR      VOLTAGE",
    "SKR1.BUSBAR VOLTAGE",
    "SKR1.Current Inc To Trafo2",
    "SKR1.Current Out To PH",
    "SKR1.DIESEL 1 STATOR CURRENT",
    "SKR1.DIESEL 1 STATOR VOLTAGE",
    "SKR1.DIESEL 2 STATOR CURRENT",
    "SKR1.HOT AIR TEMPERATURE1 U1",
    "SKR1.HOT AIR TEMPERATURE2 U1",
    "SKR1.HOT AIR TEMPERATURE3 U1",
    "SKR1.HOT AIR TEMPERATURE4 U1",
    "SKR1.HOT AIR TEMPERATURE5 U1",
    "SKR1.HOT AIR TEMPERATURE6 U1",
    "SKR1.LO GUIDE BRG METAL 1 U1",
    "SKR1.LO GUIDE BRG METAL 2 U1",
    "SKR1.LO GUIDE BRGOIL TEMP U1",
    "SKR1.LOAD LIMITERPOSITION U 1",
    "SKR1.MDB Voltage Busbar A",
    "SKR1.METAL TEMP 1 U1",
    "SKR1.OIL TEMP. U1",
    "SKR1.REACTIVE    PWR UNIT 1",
    "SKR1.REACTIVE POWER U1",
    "SKR1.ROTOR CURR  UNIT 1",
    "SKR1.ROTOR VOLT  UNIT 1",
    "SKR1.STATOR CORE TEMP1 U1",
    "SKR1.STATOR CORE TEMP2 U1",
    "SKR1.STATOR CURR UNIT 1",
    "SKR1.STATOR VOLT UNIT 1",
    "SKR1.STATOR WIND TEMP1 U1",
    "SKR1.STATOR WIND TEMP2 U1",
    "SKR1.STATOR WIND TEMP3 U1",
    "SKR1.STATOR WIND TEMP4 U1",
    "SKR1.STATOR WIND TEMP5 U1",
    "SKR1.STATOR WIND TEMP6 U1",
    "SKR1.TAIL WATER  PRESSURE",
    "SKR1.THRUST BRG  METAL 1 U1",
    "SKR1.THRUST BRG  METAL 2 U1",
    "SKR1.THRUST BRG  METAL 3 U1",
    "SKR1.TURB SPEED  DROOP UNIT 1",
    "SKR1.TURB SPEED  UNIT 1",
    "SKR1.TURBINE     DISCHARGE",
    "SKR1.UP GD&TH BRGOIL TEMP U1",
    "SKR1.UP GUIDE BRG METAL 1 U1",
    "SKR1.UP GUIDE BRG METAL 2 U1",
    "SKR1.Voltage Inc Fr 5MVA Traf",
    "SKR1.WATER UPSTREAM PRESSURE",
    "SKR1.WICKET GATE POSITION",
    #"SKR1.Discharge Debit ",
    #"SKR1.Generator Turbine Guide ",
    "SKR1.Generator Lower Guide Bearing Horizontal Vibration",
    "SKR1.Generator Lower Guide Bearing Vertical Vibration",
    "SKR1.Generator Lower Guide Bearing Axial Vibration",
    "SKR1.Generator Upper Guide Bearing Horizontal Vibration",
    "SKR1.Generator Upper Guide Bearing Vertical Vibration",
    "SKR1.Generator Upper Guide Bearing Axial Vibration",
    "SKR1.Generator Turbine Guide Bearing Horizontal Vibration",
    "SKR1.Generator Turbine Guide Bearing Vertical Vibration",
    "SKR1.Generator Turbine Guide Bearing Axial Vibration"
]

UNIT1_TARGET_COLS = [
    # "SKR1.LO GUIDE BRGOIL TEMP U1",
    # "SKR1.METAL TEMP 1 U1",
    # "SKR1.OIL TEMP. U1",
    # "SKR1.UP GD&TH BRGOIL TEMP U1",
    # "SKR1.THRUST BRG  METAL 1 U1",
    # "SKR1.THRUST BRG  METAL 2 U1",
    # "SKR1.THRUST BRG  METAL 3 U1",
    # "SKR1.STATOR CORE TEMP1 U1",
    # "SKR1.STATOR CORE TEMP2 U1",
    # "SKR1.STATOR WIND TEMP1 U1",
    # "SKR1.STATOR WIND TEMP2 U1",
    # "SKR1.STATOR WIND TEMP3 U1",
    # "SKR1.STATOR WIND TEMP4 U1",
    # "SKR1.STATOR WIND TEMP5 U1",
    # "SKR1.STATOR WIND TEMP6 U1",
    "SKR1.Generator Lower Guide Bearing Horizontal Vibration",
    "SKR1.Generator Lower Guide Bearing Vertical Vibration",
    "SKR1.Generator Lower Guide Bearing Axial Vibration",
    "SKR1.Generator Upper Guide Bearing Horizontal Vibration",
    "SKR1.Generator Upper Guide Bearing Vertical Vibration",
    "SKR1.Generator Upper Guide Bearing Axial Vibration",
    "SKR1.Generator Turbine Guide Bearing Horizontal Vibration",
    "SKR1.Generator Turbine Guide Bearing Vertical Vibration",
    "SKR1.Generator Turbine Guide Bearing Axial Vibration"
]

UNIT1_TARGET_COLS_PRED = [
    "SKR1.LO GUIDE BRGOIL TEMP U1.prediksi",
    "SKR1.METAL TEMP 1 U1.prediksi",
    "SKR1.OIL TEMP. U1.prediksi",
    "SKR1.UP GD&TH BRGOIL TEMP U1.prediksi",
    "SKR1.THRUST BRG  METAL 1 U1.prediksi",
    "SKR1.THRUST BRG  METAL 2 U1.prediksi",
    "SKR1.THRUST BRG  METAL 3 U1.prediksi",
    "SKR1.STATOR CORE TEMP1 U1.prediksi",
    "SKR1.STATOR CORE TEMP2 U1.prediksi",
    "SKR1.STATOR WIND TEMP1 U1.prediksi",
    "SKR1.STATOR WIND TEMP2 U1.prediksi",
    "SKR1.STATOR WIND TEMP3 U1.prediksi",
    "SKR1.STATOR WIND TEMP4 U1.prediksi",
    "SKR1.STATOR WIND TEMP5 U1.prediksi",
    "SKR1.STATOR WIND TEMP6 U1.prediksi",
    "SKR1.Generator Lower Guide Bearing Horizontal Vibration.prediksi",
    "SKR1.Generator Lower Guide Bearing Vertical Vibration.prediksi",
    "SKR1.Generator Lower Guide Bearing Axial Vibration.prediksi",
    "SKR1.Generator Upper Guide Bearing Horizontal Vibration.prediksi",
    "SKR1.Generator Upper Guide Bearing Vertical Vibration.prediksi",
    "SKR1.Generator Upper Guide Bearing Axial Vibration.prediksi",
    "SKR1.Generator Turbine Guide Bearing Horizontal Vibration.prediksi",
    "SKR1.Generator Turbine Guide Bearing Vertical Vibration.prediksi",
    "SKR1.Generator Turbine Guide Bearing Axial Vibration.prediksi",
]