UNIT1_INPUT_COLS  = [
    "SKR1.LO GUIDE BRGOIL TEMP U1",
    "SKR1.METAL TEMP 1 U1",	
    "SKR1.OIL TEMP. U1",	
    "SKR1.STATOR CORE TEMP1 U1",	
    "SKR1.STATOR CORE TEMP2 U1",	
    "SKR1.STATOR WIND TEMP1 U1",	
    "SKR1.STATOR WIND TEMP2 U1",	
    "SKR1.STATOR WIND TEMP3 U1",
    "SKR1.STATOR WIND TEMP4 U1",
    "SKR1.STATOR WIND TEMP5 U1",
    "SKR1.STATOR WIND TEMP6 U1",
    "SKR1.THRUST BRG  METAL 1 U1",
    "SKR1.THRUST BRG  METAL 2 U1",
    "SKR1.THRUST BRG  METAL 3 U1",
    "SKR1.UP GD&TH BRGOIL TEMP U1"
]

UNIT1_TARGET_COLS = [
    "SKR1.LO GUIDE BRGOIL TEMP U1",
    "SKR1.METAL TEMP 1 U1",	
    "SKR1.OIL TEMP. U1",	
    "SKR1.STATOR CORE TEMP1 U1",	
    "SKR1.STATOR CORE TEMP2 U1",	
    "SKR1.STATOR WIND TEMP1 U1",	
    "SKR1.STATOR WIND TEMP2 U1",	
    "SKR1.STATOR WIND TEMP3 U1",
    "SKR1.STATOR WIND TEMP4 U1",
    "SKR1.STATOR WIND TEMP5 U1",
    "SKR1.STATOR WIND TEMP6 U1",
    "SKR1.THRUST BRG  METAL 1 U1",
    "SKR1.THRUST BRG  METAL 2 U1",
    "SKR1.THRUST BRG  METAL 3 U1",
    "SKR1.UP GD&TH BRGOIL TEMP U1"
]