from app.configs.base_conf import settings
def unit_config(unit: str):
    match unit:
        case "1":
            return {
                "SENSOR_NAME_QUERY": "SKR1%",
                "SENSOR_NAME_QUERY_STAR": "SKR1*",
                "PREDICT_UNIT":  1,
                "FREQ": '5T',
                "SENSOR_NAME_QUERY_VIBRATION": "SKR2.Generator%",

                "LSTM_MODEL_PATH": settings.BASE_PATH + "storage/lstm/unit1/final_lstm_model.keras",
                "LSTM_SCALER_X_PATH": settings.BASE_PATH + "storage/lstm/unit1/scaler_X.save",
                "LSTM_SCALER_Y_PATH": settings.BASE_PATH + "storage/lstm/unit1/scaler_y.save",
                "LSTM_PREPARE_DATA": 7,
                "LSTM_TIMESTEPS": 2016,
                "LSTM_HORIZON": 2016,
                "LSTM_OUTPUT_DIR": settings.BASE_PATH + "storage/lstm/unit1/result/",
                "LSTM_INPUT_COLS": [
                    "SKR1.24VDC VOLTAGE BUSBAR A",
                    "SKR1.24VDC VOLTAGE BUSBAR B",
                    "SKR1.ACTIVE POWER U1",
                    "SKR1.ACTIVE PWR",
                    "SKR1.BUSBAR      VOLTAGE",
                    "SKR1.BUSBAR VOLTAGE",
                    "SKR1.Current Inc To Trafo2",
                    "SKR1.Current Out To PH",
                    "SKR1.DIESEL 1 STATOR CURRENT",
                    "SKR1.DIESEL 1 STATOR VOLTAGE",
                    "SKR1.DIESEL 2 STATOR CURRENT",
                    "SKR1.HOT AIR TEMPERATURE1 U1",
                    "SKR1.HOT AIR TEMPERATURE2 U1",
                    "SKR1.HOT AIR TEMPERATURE3 U1",
                    "SKR1.HOT AIR TEMPERATURE4 U1",
                    "SKR1.HOT AIR TEMPERATURE5 U1",
                    "SKR1.HOT AIR TEMPERATURE6 U1",
                    "SKR1.LO GUIDE BRG METAL 1 U1",
                    "SKR1.LO GUIDE BRG METAL 2 U1",
                    "SKR1.LO GUIDE BRGOIL TEMP U1",
                    "SKR1.LOAD LIMITERPOSITION U 1",
                    "SKR1.MDB Voltage Busbar A",
                    "SKR1.METAL TEMP 1 U1",
                    "SKR1.OIL TEMP. U1",
                    "SKR1.REACTIVE    PWR UNIT 1",
                    "SKR1.REACTIVE POWER U1",
                    "SKR1.ROTOR CURR  UNIT 1",
                    "SKR1.ROTOR VOLT  UNIT 1",
                    "SKR1.STATOR CORE TEMP1 U1",
                    "SKR1.STATOR CORE TEMP2 U1",
                    "SKR1.STATOR CURR UNIT 1",
                    "SKR1.STATOR VOLT UNIT 1",
                    "SKR1.STATOR WIND TEMP1 U1",
                    "SKR1.STATOR WIND TEMP2 U1",
                    "SKR1.STATOR WIND TEMP3 U1",
                    "SKR1.STATOR WIND TEMP4 U1",
                    "SKR1.STATOR WIND TEMP5 U1",
                    "SKR1.STATOR WIND TEMP6 U1",
                    "SKR1.TAIL WATER  PRESSURE",
                    "SKR1.THRUST BRG  METAL 1 U1",
                    "SKR1.THRUST BRG  METAL 2 U1",
                    "SKR1.THRUST BRG  METAL 3 U1",
                    "SKR1.TURB SPEED  DROOP UNIT 1",
                    "SKR1.TURB SPEED  UNIT 1",
                    "SKR1.TURBINE     DISCHARGE",
                    "SKR1.UP GD&TH BRGOIL TEMP U1",
                    "SKR1.UP GUIDE BRG METAL 1 U1",
                    "SKR1.UP GUIDE BRG METAL 2 U1",
                    "SKR1.Voltage Inc Fr 5MVA Traf",
                    "SKR1.WATER UPSTREAM PRESSURE",
                    "SKR1.WICKET GATE POSITION",
                    #"SKR1.Discharge Debit ",
                    #"SKR1.Generator Turbine Guide ",
                    "SKR1.Generator Lower Guide Bearing Horizontal Vibration",
                    "SKR1.Generator Lower Guide Bearing Vertical Vibration",
                    "SKR1.Generator Lower Guide Bearing Axial Vibration",
                    "SKR1.Generator Upper Guide Bearing Horizontal Vibration",
                    "SKR1.Generator Upper Guide Bearing Vertical Vibration",
                    "SKR1.Generator Upper Guide Bearing Axial Vibration",
                    "SKR1.Generator Turbine Guide Bearing Horizontal Vibration",
                    "SKR1.Generator Turbine Guide Bearing Vertical Vibration",
                    "SKR1.Generator Turbine Guide Bearing Axial Vibration"
                ],
                "LSTM_TARGET_COLS": [
                    "SKR1.LO GUIDE BRGOIL TEMP U1.prediksi",
                    "SKR1.METAL TEMP 1 U1.prediksi",
                    "SKR1.OIL TEMP. U1.prediksi",
                    "SKR1.UP GD&TH BRGOIL TEMP U1.prediksi",
                    "SKR1.THRUST BRG  METAL 1 U1.prediksi",
                    "SKR1.THRUST BRG  METAL 2 U1.prediksi",
                    "SKR1.THRUST BRG  METAL 3 U1.prediksi",
                    "SKR1.STATOR CORE TEMP1 U1.prediksi",
                    "SKR1.STATOR CORE TEMP2 U1.prediksi",
                    "SKR1.STATOR WIND TEMP1 U1.prediksi",
                    "SKR1.STATOR WIND TEMP2 U1.prediksi",
                    "SKR1.STATOR WIND TEMP3 U1.prediksi",
                    "SKR1.STATOR WIND TEMP4 U1.prediksi",
                    "SKR1.STATOR WIND TEMP5 U1.prediksi",
                    "SKR1.STATOR WIND TEMP6 U1.prediksi",
                    "SKR1.Generator Lower Guide Bearing Horizontal Vibration.prediksi",
                    "SKR1.Generator Lower Guide Bearing Vertical Vibration.prediksi",
                    "SKR1.Generator Lower Guide Bearing Axial Vibration.prediksi",
                    "SKR1.Generator Upper Guide Bearing Horizontal Vibration.prediksi",
                    "SKR1.Generator Upper Guide Bearing Vertical Vibration.prediksi",
                    "SKR1.Generator Upper Guide Bearing Axial Vibration.prediksi",
                    "SKR1.Generator Turbine Guide Bearing Horizontal Vibration.prediksi",
                    "SKR1.Generator Turbine Guide Bearing Vertical Vibration.prediksi",
                    "SKR1.Generator Turbine Guide Bearing Axial Vibration.prediksi",
                ],

                "LGBM_MODEL_FILE": settings.BASE_PATH + "storage/lgbm/unit1/lgbm.pkl",
                "LGBM_OUTPUT_DIR": settings.BASE_PATH + "storage/lgbm/unit1/result/",
                "LGBM_INPUT_WINDOW": 6048,
                "LGBM_HORIZON": 2016,
                "LGBM_PLOT_HISTORY": 2016,
                "LGBM_INPUT": [
                    "SKR1.METAL TEMP 1 U1",
                    "SKR1.OIL TEMP. U1",
                    "SKR1.STATOR CORE TEMP1 U1",
                    "SKR1.STATOR CORE TEMP2 U1",
                    "SKR1.STATOR WIND TEMP1 U1",
                    "SKR1.STATOR WIND TEMP2 U1",
                    "SKR1.STATOR WIND TEMP3 U1",
                    "SKR1.STATOR WIND TEMP4 U1",
                    "SKR1.STATOR WIND TEMP5 U1",
                    "SKR1.STATOR WIND TEMP6 U1",
                    "SKR1.THRUST BRG  METAL 1 U1",
                    "SKR1.THRUST BRG  METAL 2 U1",
                    "SKR1.THRUST BRG  METAL 3 U1",
                    "SKR1.UP GD&TH BRGOIL TEMP U1",
                ],
                "LGBM_OUTPUT": [
                    "SKR1.METAL TEMP 1 U1",
                    "SKR1.OIL TEMP. U1",
                    "SKR1.STATOR CORE TEMP1 U1",
                    "SKR1.STATOR CORE TEMP2 U1",
                    "SKR1.STATOR WIND TEMP1 U1",
                    "SKR1.STATOR WIND TEMP2 U1",
                    "SKR1.STATOR WIND TEMP3 U1",
                    "SKR1.STATOR WIND TEMP4 U1",
                    "SKR1.STATOR WIND TEMP5 U1",
                    "SKR1.STATOR WIND TEMP6 U1",
                    "SKR1.THRUST BRG  METAL 1 U1",
                    "SKR1.THRUST BRG  METAL 2 U1",
                    "SKR1.THRUST BRG  METAL 3 U1",
                    "SKR1.UP GD&TH BRGOIL TEMP U1",
                ],
                "SENSOR_PREDICTION": [
                    "SKR1.METAL TEMP 1 U1",
                    "SKR1.OIL TEMP. U1",
                    # "SKR1.STATOR CORE TEMP1 U1",
                    # "SKR1.STATOR CORE TEMP2 U1",
                    # "SKR1.STATOR WIND TEMP1 U1",
                    # "SKR1.STATOR WIND TEMP2 U1",
                    # "SKR1.STATOR WIND TEMP3 U1",
                    # "SKR1.STATOR WIND TEMP4 U1",
                    # "SKR1.STATOR WIND TEMP5 U1",
                    # "SKR1.STATOR WIND TEMP6 U1",
                    # "SKR1.THRUST BRG  METAL 1 U1",
                    # "SKR1.THRUST BRG  METAL 2 U1",
                    # "SKR1.THRUST BRG  METAL 3 U1",
                    # "SKR1.UP GD&TH BRGOIL TEMP U1",
                ],
                "SENSOR_UPLOAD": [
                    "SKR1.METAL TEMP 1 U1.prediksi",
                    "SKR1.OIL TEMP. U1.prediksi",
                    # "SKR1.STATOR CORE TEMP1 U1.prediksi",
                    # "SKR1.STATOR CORE TEMP2 U1.prediksi",
                    # "SKR1.STATOR WIND TEMP1 U1.prediksi",
                    # "SKR1.STATOR WIND TEMP2 U1.prediksi",
                    # "SKR1.STATOR WIND TEMP3 U1.prediksi",
                    # "SKR1.STATOR WIND TEMP4 U1.prediksi",
                    # "SKR1.STATOR WIND TEMP5 U1.prediksi",
                    # "SKR1.STATOR WIND TEMP6 U1.prediksi",
                    # "SKR1.THRUST BRG  METAL 1 U1.prediksi",
                    # "SKR1.THRUST BRG  METAL 2 U1.prediksi",
                    # "SKR1.THRUST BRG  METAL 3 U1.prediksi",
                    # "SKR1.UP GD&TH BRGOIL TEMP U1.prediksi",
                ]
            }
        case "2":
            return {
                "SENSOR_NAME_QUERY": "SKR2%",
                "SENSOR_NAME_QUERY_STAR": "SKR2*",
                "PREDICT_UNIT":  2,
                "FREQ": '5T',
                "SENSOR_NAME_QUERY_VIBRATION": "SKR2.Generator%",
                "LGBM_MODEL_FILE": settings.BASE_PATH + "storage/lgbm/unit2/lgbm.pkl",
                "LGBM_OUTPUT_DIR": settings.BASE_PATH + "storage/lgbm/unit2/",
                "LGBM_INPUT_WINDOW":6048,
                "LGBM_HORIZON": 2016,
                "LGBM_PLOT_HISTORY": 2016,
                "LSTM_INPUT_COLS": [
                    "SKR2.ACTIVE PWR",
                    "SKR2.ACTIVE PWR  UNIT 2"
                    "SKR2.AROTOR CURR  UNIT 2",
                    "SKR2.HOT AIR TEMPERATURE 1 U2",
                    "SKR2.HOT AIR TEMPERATURE2 U2",
                    "SKR2.HOT AIR TEMPERATURE3 U2",
                    "SKR2.HOT AIR TEMPERATURE4 U2",
                    "SKR2.HOT AIR TEMPERATURE5 U2",
                    "SKR2.HOT AIR TEMPERATURE6 U2",
                    "SKR2.LO GUIDE BRG METAL 1 U2",
                    "SKR2.LO GUIDE BRG METAL 2 U2",
                    "SKR2.LO GUIDE BRGOIL TEMP U2",
                    "SKR2.LOAD LIMITERPOSITION U 2",
                    "SKR2.METAL TEMP 1 U2",
                    "SKR2.METAL TEMP 2 U2",
                    "SKR2.OIL TEMP. U2",
                    "SKR2.REACTIVE    PWR UNIT 2",
                    "SKR2.SPIRAL CASE PRESS UNIT 2",
                    "SKR2.STATOR CORE TEMP1 U2",
                    "SKR2.STATOR CORE TEMP2 U2",
                    "SKR2.STATOR CURR UNIT 2",
                    "SKR2.STATOR VOLT UNIT2",
                    "SKR2.STATOR WIND TEMP 4 U2",
                    "SKR2.STATOR WIND TEMP1 U2",
                    "SKR2.STATOR WIND TEMP2 U2",
                    "SKR2.STATOR WIND TEMP3 U2",
                    "SKR2.STATOR WIND TEMP5 U2",
                    "SKR2.STATOR WIND TEMP6 U2",
                    "SKR2.TAIL WATER  PRESSURE U2",
                    "SKR2.THRUST BRG  METAL 1 U2",
                    "SKR2.THRUST BRG  METAL 2 U2",
                    "SKR2.THRUST BRG  METAL 3 U2",
                    "SKR2.TURB SPEED  DROOP UNIT 2",
                    "SKR2.TURB SPEED  UNIT 2",
                    "SKR2.TURBINE     DISCHARGE",
                    "SKR2.TURBINE DISCHARGE U2",
                    "SKR2.UP GUIDE BRGMETAL TEMP 1",
                    "SKR2.UP GUIDE BRGMTL 2 U2",
                    "SKR2.UPPER GUIDE AND THRUST B",
                    "SKR2.WICKET GATE POSITION U2",
                    "SKR2.WTR UPSTREAMPRESSURE U2",
                    "SKR2.Generator Turbine Guide Bearing Horizontal Vibration",
                    "SKR2.Generator Turbine Guide Bearing Vertical Vibration",
                    "SKR2.Generator Turbine Guide Bearing Axial Vibration",
                    "SKR2.Generator Lower Guide Bearing Horizontal Vibration",
                    "SKR2.Generator Lower Guide Bearing Vertical Vibration",
                    "SKR2.Generator Lower Guide Bearing Axial Vibration",
                    "SKR2.Generator Upper Guide Bearing Horizontal Vibration",
                    "SKR2.Generator Upper Guide Bearing Vertical Vibration",
                    "SKR2.Generator Upper Guide Bearing Axial Vibration",
                    "SKR2.Discharge Debit",
                ],
                "LGBM_INPUT": [
                    "SKR2.METAL TEMP 1 U2",
                    "SKR2.METAL TEMP 2 U2",
                    "SKR2.LO GUIDE BRGOIL TEMP U2",
                    "SKR2.OIL TEMP. U2",
                    "SKR2.UP GUIDE BRGMETAL TEMP 1",
                    "SKR2.UP GUIDE BRGMTL 2 U2",
                    "SKR2.UPPER GUIDE AND THRUST B",
                    "SKR2.THRUST BRG  METAL 1 U2",
                    "SKR2.THRUST BRG  METAL 2 U2",
                    "SKR2.THRUST BRG  METAL 3 U2",
                    "SKR2.STATOR CORE TEMP1 U2",
                    "SKR2.STATOR CORE TEMP2 U2",
                    "SKR2.STATOR WIND TEMP1 U2",
                    "SKR2.STATOR WIND TEMP2 U2",
                    "SKR2.STATOR WIND TEMP3 U2",
                    "SKR2.STATOR WIND TEMP 4 U2",
                    "SKR2.STATOR WIND TEMP5 U2",
                    "SKR2.STATOR WIND TEMP6 U2",
                ],
                "LGBM_OUTPUT": [
                    "SKR2.METAL TEMP 1 U2",
                    "SKR2.METAL TEMP 2 U2",
                    "SKR2.LO GUIDE BRGOIL TEMP U2",
                    "SKR2.OIL TEMP. U2",
                    "SKR2.UP GUIDE BRGMETAL TEMP 1",
                    "SKR2.UP GUIDE BRGMTL 2 U2",
                    "SKR2.UPPER GUIDE AND THRUST B",
                    "SKR2.THRUST BRG  METAL 1 U2",
                    "SKR2.THRUST BRG  METAL 2 U2",
                    "SKR2.THRUST BRG  METAL 3 U2",
                    "SKR2.STATOR CORE TEMP1 U2",
                    "SKR2.STATOR CORE TEMP2 U2",
                    "SKR2.STATOR WIND TEMP1 U2",
                    "SKR2.STATOR WIND TEMP2 U2",
                    "SKR2.STATOR WIND TEMP3 U2",
                    "SKR2.STATOR WIND TEMP 4 U2",
                    "SKR2.STATOR WIND TEMP5 U2",
                    "SKR2.STATOR WIND TEMP6 U2",
                ],
                "SENSOR_PREDICTION": [
                    "SKR2.METAL TEMP 1 U2",
                    "SKR2.METAL TEMP 2 U2",
                    "SKR2.LO GUIDE BRGOIL TEMP U2",
                    "SKR2.OIL TEMP. U2",
                    "SKR2.UPPER GUIDE AND THRUST B",
                    "SKR2.THRUST BRG  METAL 1 U2",
                    "SKR2.THRUST BRG  METAL 2 U2",
                    "SKR2.THRUST BRG  METAL 3 U2",
                    "SKR2.STATOR CORE TEMP1 U2",
                    "SKR2.STATOR CORE TEMP2 U2",
                    "SKR2.STATOR WIND TEMP1 U2",
                    "SKR2.STATOR WIND TEMP2 U2",
                    "SKR2.STATOR WIND TEMP3 U2",
                    "SKR2.STATOR WIND TEMP 4 U2",
                    "SKR2.STATOR WIND TEMP5 U2",
                    "SKR2.STATOR WIND TEMP6 U2",
                ],
                "SENSOR_UPLOAD": [
                    "SKR2.METAL TEMP 1 U2.prediksi",
                    "SKR2.METAL TEMP 2 U2.prediksi",
                    "SKR2.LO GUIDE BRGOIL TEMP U2.prediksi",
                    "SKR2.OIL TEMP. U2.prediksi",
                    "SKR2.UPPER GUIDE AND THRUST B.prediksi",
                    "SKR2.THRUST BRG  METAL 1 U2.prediksi",
                    "SKR2.THRUST BRG  METAL 2 U2.prediksi",
                    "SKR2.THRUST BRG  METAL 3 U2.prediksi",
                    "SKR2.STATOR CORE TEMP1 U2.prediksi",
                    "SKR2.STATOR CORE TEMP2 U2.prediksi",
                    "SKR2.STATOR WIND TEMP1 U2.prediksi",
                    "SKR2.STATOR WIND TEMP2 U2.prediksi",
                    "SKR2.STATOR WIND TEMP3 U2.prediksi",
                    "SKR2.STATOR WIND TEMP 4 U2.prediksi",
                    "SKR2.STATOR WIND TEMP5 U2.prediksi",
                    "SKR2.STATOR WIND TEMP6 U2.prediksi",
                ],
            }
        case "3":
            return {
                "SENSOR_NAME_QUERY": "SKR3%",
                "SENSOR_NAME_QUERY_STAR": "SKR3*",
                "PREDICT_UNIT":  3,
                "FREQ": '5T',
                "SENSOR_NAME_QUERY_VIBRATION": "SKR3.Generator%",
                "LGBM_MODEL_FILE": settings.BASE_PATH + "storage/lgbm/unit3/lgbm.pkl",
                "LGBM_OUTPUT_DIR": settings.BASE_PATH + "storage/lgbm/unit3/",
                "LGBM_INPUT_WINDOW":6048,
                "LGBM_HORIZON": 2016,
                "LGBM_PLOT_HISTORY": 2016,
                "LGBM_INPUT": [
                    "SKR3.METAL TEMP 1 U3",
                    "SKR3.METAL TEMP 2 U3",
                    "SKR3.OIL TEMP. U3",
                    "SKR3.UP GD&TH BRGOIL TEMP U3",
                    "SKR3.LO GUIDE BRGOIL TEMP U3",
                    "SKR3.THRUST BRG  METAL 1 U3",
                    "SKR3.THRUST BRG  METAL 2 U3",
                    "SKR3.THRUST BRG  METAL 3 U3",
                    "SKR3.STATOR CORE TEMP1 U3",
                    "SKR3.STATOR CORE TEMP2 U3",
                    "SKR3.STATOR WIND TEMP1 U3",
                    "SKR3.STATOR WIND TEMP2 U3",
                    "SKR3.STATOR WIND TEMP3 U3",
                    "SKR3.STATOR WIND TEMP4 U3",
                    "SKR3.STATOR WIND TEMP5 U3",
                    "SKR3.STATOR WIND TEMP6 U3",
                ],
                "LGBM_OUTPUT": [
                    "SKR3.METAL TEMP 1 U3",
                    "SKR3.METAL TEMP 2 U3",
                    "SKR3.OIL TEMP. U3",
                    "SKR3.UP GD&TH BRGOIL TEMP U3",
                    "SKR3.LO GUIDE BRGOIL TEMP U3",
                    "SKR3.THRUST BRG  METAL 1 U3",
                    "SKR3.THRUST BRG  METAL 2 U3",
                    "SKR3.THRUST BRG  METAL 3 U3",
                    "SKR3.STATOR CORE TEMP1 U3",
                    "SKR3.STATOR CORE TEMP2 U3",
                    "SKR3.STATOR WIND TEMP1 U3",
                    "SKR3.STATOR WIND TEMP2 U3",
                    "SKR3.STATOR WIND TEMP3 U3",
                    "SKR3.STATOR WIND TEMP4 U3",
                    "SKR3.STATOR WIND TEMP5 U3",
                    "SKR3.STATOR WIND TEMP6 U3",
                ],
                "SENSOR_PREDICTION": [
                    "SKR3.METAL TEMP 1 U3",
                    "SKR3.METAL TEMP 2 U3",
                    "SKR3.OIL TEMP. U3",
                    "SKR3.UP GD&TH BRGOIL TEMP U3",
                    # "SKR3.LO GUIDE BRGOIL TEMP U3",
                    # "SKR3.THRUST BRG  METAL 1 U3",
                    # "SKR3.THRUST BRG  METAL 2 U3",
                    # "SKR3.THRUST BRG  METAL 3 U3",
                    # "SKR3.STATOR CORE TEMP1 U3",
                    # "SKR3.STATOR CORE TEMP2 U3",
                    # "SKR3.STATOR WIND TEMP1 U3",
                    # "SKR3.STATOR WIND TEMP2 U3",
                    # "SKR3.STATOR WIND TEMP3 U3",
                    # "SKR3.STATOR WIND TEMP4 U3",
                    # "SKR3.STATOR WIND TEMP5 U3",
                    # "SKR3.STATOR WIND TEMP6 U3",
                ],
                "SENSOR_UPLOAD": [
                    "SKR3.METAL TEMP 1 U3.prediksi",
                    "SKR3.METAL TEMP 2 U3.prediksi",
                    "SKR3.OIL TEMP. U3.prediksi",
                    "SKR3.UP GD&TH BRGOIL TEMP U3.prediksi",
                    # "SKR3.LO GUIDE BRGOIL TEMP U3.prediksi",
                    # "SKR3.THRUST BRG  METAL 1 U3.prediksi",
                    # "SKR3.THRUST BRG  METAL 2 U3.prediksi",
                    # "SKR3.THRUST BRG  METAL 3 U3.prediksi",
                    # "SKR3.STATOR CORE TEMP1 U3.prediksi",
                    # "SKR3.STATOR CORE TEMP2 U3.prediksi",
                    # "SKR3.STATOR WIND TEMP1 U3.prediksi",
                    # "SKR3.STATOR WIND TEMP2 U3.prediksi",
                    # "SKR3.STATOR WIND TEMP3 U3.prediksi",
                    # "SKR3.STATOR WIND TEMP4 U3.prediksi",
                    # "SKR3.STATOR WIND TEMP5 U3.prediksi",
                    # "SKR3.STATOR WIND TEMP6 U3.prediksi",
                ],
            }
        case "4":
            return {
                "SENSOR_NAME_QUERY": "SKR4%",
                "SENSOR_NAME_QUERY_STAR": "SKR4*",
                "PREDICT_UNIT":  4,
                "FREQ": '5T',
                "SENSOR_NAME_QUERY_VIBRATION": "SKR4.Generator%",
                "LGBM_MODEL_FILE": settings.BASE_PATH + "storage/lgbm/unit4/lgbm.pkl",
                "LGBM_OUTPUT_DIR": settings.BASE_PATH + "storage/lgbm/unit4/",
                "LGBM_INPUT_WINDOW":6048,
                "LGBM_HORIZON": 2016,
                "LGBM_PLOT_HISTORY": 2016,
                "LGBM_INPUT": [
                    "SKR4.LO GUIDE BRGOIL TEMP U4",
                    "SKR4.UP GD&TH BRGOIL TEMP U4",
                    "SKR4.METAL TEMP 2 U4",
                    "SKR4.THRUST BRG  METAL 1 U4",
                    "SKR4.THRUST BRG  METAL 2 U4",
                    "SKR4.THRUST BRG  METAL 3 U4",
                    "SKR4.STATOR CORE TEMP1 UNIT4",
                    "SKR4.STATOR CORE TEMP 2 U4",
                    "SKR4.STATOR WIND TEMP 1 U4",
                    "SKR4.STATOR WIND TEMP 2 U4",
                    "SKR4.STATOR WIND TEMP3 UNIT4",
                    "SKR4.STATOR WIND TEMP4 UNIT4",
                    "SKR4.STATOR WIND TEMP5 UNIT4",
                    "SKR4.STATOR WIND TEMP 6 U4",
                ],
                "LGBM_OUTPUT": [
                    "SKR4.LO GUIDE BRGOIL TEMP U4",
                    "SKR4.UP GD&TH BRGOIL TEMP U4",
                    "SKR4.METAL TEMP 2 U4",
                    "SKR4.THRUST BRG  METAL 1 U4",
                    "SKR4.THRUST BRG  METAL 2 U4",
                    "SKR4.THRUST BRG  METAL 3 U4",
                    "SKR4.STATOR CORE TEMP1 UNIT4",
                    "SKR4.STATOR CORE TEMP 2 U4",
                    "SKR4.STATOR WIND TEMP 1 U4",
                    "SKR4.STATOR WIND TEMP 2 U4",
                    "SKR4.STATOR WIND TEMP3 UNIT4",
                    "SKR4.STATOR WIND TEMP4 UNIT4",
                    "SKR4.STATOR WIND TEMP5 UNIT4",
                    "SKR4.STATOR WIND TEMP 6 U4",
                ],
                "SENSOR_PREDICTION": [
                    "SKR4.LO GUIDE BRGOIL TEMP U4",
                    "SKR4.UP GD&TH BRGOIL TEMP U4",
                    "SKR4.METAL TEMP 2 U4",
                    "SKR4.THRUST BRG  METAL 1 U4",
                    "SKR4.THRUST BRG  METAL 2 U4",
                    # "SKR4.THRUST BRG  METAL 3 U4",
                    # "SKR4.STATOR CORE TEMP1 UNIT4",
                    # "SKR4.STATOR CORE TEMP 2 U4",
                    # "SKR4.STATOR WIND TEMP 1 U4",
                    # "SKR4.STATOR WIND TEMP 2 U4",
                    # "SKR4.STATOR WIND TEMP3 UNIT4",
                    # "SKR4.STATOR WIND TEMP4 UNIT4",
                    # "SKR4.STATOR WIND TEMP5 UNIT4",
                    # "SKR4.STATOR WIND TEMP 6 U4",
                ],
                "SENSOR_UPLOAD": [
                    "SKR4.LO GUIDE BRGOIL TEMP U4.prediksi",
                    "SKR4.UP GD&TH BRGOIL TEMP U4.prediksi",
                    "SKR4.METAL TEMP 2 U4.prediksi",
                    "SKR4.THRUST BRG  METAL 1 U4.prediksi",
                    "SKR4.THRUST BRG  METAL 2 U4.prediksi",
                    # "SKR4.THRUST BRG  METAL 3 U4.prediksi",
                    # "SKR4.STATOR CORE TEMP1 UNIT4.prediksi",
                    # "SKR4.STATOR CORE TEMP 2 U4.prediksi",
                    # "SKR4.STATOR WIND TEMP 1 U4.prediksi",
                    # "SKR4.STATOR WIND TEMP 2 U4.prediksi",
                    # "SKR4.STATOR WIND TEMP3 UNIT4.prediksi",
                    # "SKR4.STATOR WIND TEMP4 UNIT4.prediksi",
                    # "SKR4.STATOR WIND TEMP5 UNIT4.prediksi",
                    # "SKR4.STATOR WIND TEMP 6 U4.prediksi",
                ],
            }
        case _:
            raise ValueError(f"No config defined for unit = {unit}")
        

